import type { Metadata } from "next";
import { openSans } from "@/app/ui/fonts";

import ClientListeners from "./clientListeners";
import Navbar from "@/components/navbar/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lukas Stuart Fry's Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${openSans.className} min-h-screen bg-gradient-to-br from-slate-50 to-slate-300 pb-24 antialiased transition-all duration-500 dark:from-slate-800 dark:to-slate-900 dark:text-slate-100
          `}
      >
        <Navbar />
        <ClientListeners />
        {children}
      </body>
    </html>
  );
}
