import type { Metadata } from "next";
import { openSans } from "@/app/ui/fonts";
import Navbar from "@/components/navbar/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lukas Stuart Fry's Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} container m-auto min-h-screen max-w-5xl bg-gray-100 p-12 antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
